<h2><i class="fa address-book-o">Connectez-vous</i></h2>
<form class="generic-form" method="post">
    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p><?= $errorMessage ?></p>
    </aside>
    <fieldset>
        <ul>
            <li>
                <label for="email">E-mail</label>
                <input type="text" name="email" id="email" value="<?=$email ?>">
            </li>
            <li>
                <label for="password">mot de passe</label>
                <input type="password" name="password" id="password">
            </li>

        </ul>
    </fieldset>
    <ul>
        <li>
            <input class="button button-primary" type="submit" value="Identification">
            <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
        </li>
    </ul>
</form>