<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <?php if($session->isLogged() ): ?>
            <!-- si l'utilisateur est connecté -->
            <li>
                <?php if( $session->isLogged() ): ?>
                    Bonjour <?= strip_tags($session->getFullName()) ?>
                <?php endif ?>
            </li>
            <li><a href="<?= $requestUrl ?>/user/logout" class="button button-primary">Déconnexion</a></li>
            <li><a href="<?= $requestUrl ?>/booking" class="button button-primary">Réservez votre table</a></li>
        <?php else: ?>
            <!-- si l'utilisateur n'est pas connecté -->
            <li><a href="<?= $requestUrl ?>/user/register" class="button button-primary">Inscription</a></li>
            <li><a href="<?= $requestUrl ?>/user/login" class="button button-primary">Connexion</a></li>
        <?php endif ?>
        <?php if($session->isAdmin() ): ?>
            <li><a href="<?= $requestUrl ?>/admin/dashboard" class="button button-primary">Administration</a></li>
        <?php endif ?>

        <!-- Code HTML/PHP à écrire -->
    </ul>
</nav>

<main>
    <?php if($flashBag->hasMessages()) :?>
        <aside class="notice hidden">
            <?php foreach($flashBag->fetchMessages() as $message): ?>
                <p><?= $message ?></p>
            <?php endforeach; ?>
        </aside>
    <?php endif ?>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>